import cv2
import pickle
import numpy as np

'''Loads pickle file generated by frame_accum.py and show camera wise image'''
a = open('HeatMap_Gulshan022023-02-08 11:54:38.175412','rb')
f = pickle.load(a)
for i in f.values():
    for j in i:
        cv2.imshow('output',j)
        cv2.waitKey(0)
